# Generated by Django 3.2.5 on 2021-09-08 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20210805_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='id_cate',
        ),
        migrations.AlterField(
            model_name='article',
            name='id_cate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id_sub_cate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.subcategory'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
