# Generated by Django 3.2.5 on 2021-09-11 04:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20210908_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('published', models.DateField(default=datetime.datetime.now)),
                ('id_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.comment')),
            ],
        ),
    ]
